version: "3"
services:
    transmission:
        image: haugene/transmission-openvpn
        container_name: transmission
        restart: always # unless-stopped
        dns:
            - 1.1.1.1
        ports:
            - "9091:9091"
        environment:
            - TZ=America/Los_Angeles
            - PUID=1000
            - PGID=1000
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=us_silicon_valley
            - OPENVPN_USERNAME=${VPN_USER}
            - OPENVPN_PASSWORD=${VPN_PASSWORD}
            - "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - TRANSMISSION_PEER_PORT_RANDOM_ON_START=true
            - TRANSMISSION_BLOCKLIST_ENABLED=true
            - TRANSMISSION_BLOCKLIST_URL="https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz"
            - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
            - TRANSMISSION_IDLE_SEEDING_LIMIT=240
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_RATIO_LIMIT=2
            - TRANSMISSION_HOME=/config/transmission-home
            - TRANSMISSION_DOWNLOAD_DIR=/data/Movies
            - TRANSMISSION_INCOMPLETE_DIR=/data/.incomplete
            - TRANSMISSION_WATCH_DIR=/config/watch
            - LOCAL_NETWORK=192.168.0.0/16
        volumes:
            - ${TRANSMISSION_DATA}:/data
            - ${TRANSMISSION_CONFIG}/:/config
        cap_add: 
            - NET_ADMIN

    flexget:
        image: wiserain/flexget
        container_name: flexget
        restart: on-failure:5
        ports :
            - 5050:5050
        environment:
            - TZ=America/Los_Angeles
            - PUID=1000
            - PGID=1000
            - FG_WEBUI_PASSWD=${FLEXGET_PASSWORD}
        dns:
            - 1.1.1.1
        volumes:
            - ${TRANSMISSION_CONFIG}/flexget-config/:/config
        cap_add:
            - NET_ADMIN

