name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      flexget_version:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.flexget_version }}\"
